[theme]
primaryColor = "#FF6600"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#E0E0E0"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
